# Copyright 2026 HM Revenue & Customs
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

include "frontend.conf"

appName="operational-metrics-frontend"

play.http.router = prod.Routes

play.http.errorHandler = "handlers.ErrorHandler"

play.modules.enabled += "uk.gov.hmrc.play.bootstrap.HttpClientV2Module"
play.modules.enabled += "uk.gov.hmrc.internalauth.client.modules.InternalAuthModule"
play.modules.enabled += "config.Module"

play.filters.enabled += play.filters.csp.CSPFilter

play.i18n.langs = ["en", "cy"]

microservice {
  services {

    internal-auth {
      protocol = http
      host     = localhost
      port     = 8470
    }

    operational-metrics {
      protocol = http
      host     = localhost
      port     = 8863
    }

    menu-bar {
      protocol = http 
      host     = localhost 
      port     = 9999
    }
  }
}

catalogue-wrapper {
  assets-prefix     = "/operational-metrics-frontend/catalogue-wrapper/assets"
  quick-search-path = "/operational-metrics-frontend/catalogue-wrapper/quicksearch"
}

contact-frontend {
  host      = "http://localhost:9250"
  serviceId = "operational-metrics-frontend"
}

timeout-dialog {
  timeout   = 900
  countdown = 120
}

session {
  timeoutSeconds = 900
}

host = "http://localhost:9000"

accessibility-statement{
  service-path = "/operational-metrics-frontend"
}

tracking-consent-frontend {
  gtm.container = "transitional"
}

play-frontend-hmrc {
    useRebrand = false
}


features {
  welsh-translation: true
}
